# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iQuHack-Organ-Donations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iQuHack-Organ-Donations

  target 'iQuHack-Organ-DonationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iQuHack-Organ-DonationsUITests' do
    # Pods for testing
  end

end
